// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/sugar-cat7/vspo-common-api/domain/services (interfaces: YouTubeService)

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	entities "github.com/sugar-cat7/vspo-common-api/domain/entities"
)

// MockYouTubeService is a mock of YouTubeService interface.
type MockYouTubeService struct {
	ctrl     *gomock.Controller
	recorder *MockYouTubeServiceMockRecorder
}

// MockYouTubeServiceMockRecorder is the mock recorder for MockYouTubeService.
type MockYouTubeServiceMockRecorder struct {
	mock *MockYouTubeService
}

// NewMockYouTubeService creates a new mock instance.
func NewMockYouTubeService(ctrl *gomock.Controller) *MockYouTubeService {
	mock := &MockYouTubeService{ctrl: ctrl}
	mock.recorder = &MockYouTubeServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockYouTubeService) EXPECT() *MockYouTubeServiceMockRecorder {
	return m.recorder
}

// GetPlaylists mocks base method.
func (m *MockYouTubeService) GetPlaylists() ([]entities.YTYouTubePlaylistResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPlaylists")
	ret0, _ := ret[0].([]entities.YTYouTubePlaylistResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPlaylists indicates an expected call of GetPlaylists.
func (mr *MockYouTubeServiceMockRecorder) GetPlaylists() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPlaylists", reflect.TypeOf((*MockYouTubeService)(nil).GetPlaylists))
}

// GetSongs mocks base method.
func (m *MockYouTubeService) GetSongs(arg0 []string) ([]entities.YTVideoListResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSongs", arg0)
	ret0, _ := ret[0].([]entities.YTVideoListResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSongs indicates an expected call of GetSongs.
func (mr *MockYouTubeServiceMockRecorder) GetSongs(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSongs", reflect.TypeOf((*MockYouTubeService)(nil).GetSongs), arg0)
}
